from datetime import datetime
from app.core.database import SessionLocal
from app.models.user import User
from app.models.device import Device

def main():
    # 1. Create a new DB session
    db = SessionLocal()

    try:
        # 2. Create a User object (NOT yet in DB)
        user = User(
            email="test@example.com",
            password_hash="fake_hashed_password",
            created_at=datetime.utcnow(),
            last_login=None,
        )

        # 3. Tell SQLAlchemy: "track this object"
        db.add(user)

        # 4. Flush so user_id is generated by MySQL
        db.flush()

        # At this point:
        # user.user_id is now populated
        print(f"Created user with ID: {user.user_id}")

        # 5. Create a Device linked to that user
        device = Device(
            user_id=user.user_id,
            device_name="Old Android Phone",
            status="ONLINE",
            last_heartbeat=datetime.utcnow(),
            storage_capacity=128 * 1024 * 1024 * 1024,   # 128 GB
            available_storage=120 * 1024 * 1024 * 1024, # 120 GB
        )

        # 6. Track device object
        db.add(device)

        # 7. Commit the transaction (THIS is when DB is written)
        db.commit()

        print(f"Created device with ID: {device.device_id}")

    except Exception as e:
        # 8. If anything fails, undo everything
        db.rollback()
        raise e

    finally:
        # 9. Always close the session
        db.close()

if __name__ == "__main__":
    main()
